#! /usr/bin/env python3
# -*- coding=utf-8 -*-

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fibonacci():
    a = 1
    b = 2
    res = [2]
    temp = 0
    while True:
        temp = a+b
        if temp > 4000000:
            break
        if temp % 2 == 0:
            res.append(temp)
        a = b
        b = temp
    return res

c = fibonacci()
print(c[:])
print(sum(c))


def enroll(name, gender, age=6, city='Beijing'):
    print('name:', name)
    print('gender:', gender)
    print('age:', age)
    print('city:', city)

print(enroll('horace', 38))

def f1(a, b, c=0, *args, **kw):
    print('a =', a, 'b =', b, 'c =', c, 'args =', args, 'kw =', kw)

def f2(a, b, c=0, *, d, **kw):
    print('a =', a, 'b =', b, 'c =', c, 'd =', d, 'kw =', kw)

print(f1(1, 2, 3, 'a', 'b'))